using System;
using System.Windows;
using System.Windows.Input;
using TetrisEngine;

namespace TetrisClient {
    public partial class GamePage {
        public TetrisGame Game;

        public GamePage() {
            InitializeComponent();
        }

        /// <summary>
        /// Initialize the game page to be ready for use.
        /// </summary>
        /// <param name="seed">The seed for the random queue generator.
        /// It is optional, so if it's left open the seed will be generated by the game.</param>
        public void Initialize(int seed = 0) {
            // Register the event listeners for key presses.
            RegisterKeyListener(KeyPressed);

            // Create new Game object with the amount of rows and columns that is being played with,
            // together with the randomness seed.
            Game = new TetrisGame(Constants.ROWS, Constants.COLUMNS, seed);

            // Initialize the game
            Game.InitializeGame();

            // Add the UpdateTick EventHandler to the game's timer's interval callback.
            Game.AddTimerListener(UpdateTick);

            // Start the game.
            Game.StartGame();

            // Update the page with the new changes from starting the game.
            Update();
        }

        /// <summary>
        /// The method that handles the update task. Updates the board, queue and score.
        /// </summary>
        private void UpdateTick(object sender, EventArgs e) {
            Dispatcher.Invoke(Update);
        }

        /// <summary>
        /// The method that handles updating the entire page with changes.
        /// Handles whether the game has ended, updates the GameGrid, QueueGrid and the score.
        /// </summary>
        private void Update() {
            if (Game.GameState == GameState.OVER)
                EndGame();

            GameGrid.UpdateBoard(Game.Board);
            QueueGrid.UpdateBoard(Game.Queue);
            UpdateScore();
        }

        /// <summary>
        /// Called when the game's GameState indicates the game has ended.
        /// Shows the GameOverScreen and removes the key listeners.
        /// </summary>
        private void EndGame() {
            GameOverScreen.Visibility = Visibility.Visible;
            RemoveKeyListener(KeyPressed);
        }

        /// <summary>
        /// Updates the score with any changes from the game engine.
        /// </summary>
        private void UpdateScore() {
            PointsLabel.Content = Game.Points;
            LinesLabel.Content = Game.Lines;
        }

        /// <summary>
        /// The event handler that handles key presses. Only space, up-down-left-right and ASDW are handled here.
        /// </summary>
        private void KeyPressed(object sender, KeyEventArgs keyPress) {
            switch (keyPress.Key) {
                default:
                    return;
                case Key.A:
                case Key.Left:
                    Game.MoveLeft();
                    break;
                case Key.S:
                case Key.Down:
                    Game.MoveDown();
                    break;
                case Key.D:
                case Key.Right:
                    Game.MoveRight();
                    break;
                case Key.W:
                case Key.Up:
                    if (!Game.Rotate(Direction.RIGHT))
                        Game.Rotate(Direction.LEFT);
                    break;
                case Key.Space:
                    Game.MoveDownHard();
                    break;
            }

            // Update the game board after handling an action
            Update();
        }


        /// <summary>
        /// Subscribe to the KeyDown event with the given event handler.
        /// </summary>
        /// <param name="method">The event handler that needs to be called when a key is pressed.</param>
        public void RegisterKeyListener(KeyEventHandler method) {
            var window = Window.GetWindow(this);
            window.KeyDown += method;
        }


        /// <summary>
        /// Removes the given event handler from the KeyDown event callback.
        /// </summary>
        /// <param name="method">The event handler that needs to be removed from the callback</param>
        public void RemoveKeyListener(KeyEventHandler method) {
            var window = Window.GetWindow(this);
            window.KeyDown -= method;
        }
    }
}